### STORE PROCEDURE
/*
STORE PROCEDURE IN MYSQL IS APREDEFINED SET OF SQL STATEMNENTS THAT 
ARE STORED IN THE DATABSE AND CAN BE EXECUTED( CALLED) WHENEVER NEEDED.
THINK OF IT LIKE A FUNCTION IN PROGRAMMING - YOU WRITE THE LOGIC ONCE AND THEN REUSE IT MULTIPLE TIMES.
*/

DELIMITER //
CREATE PROCEDURE FIRST_PROCEDURE(IN P_ID INT,IN P_NAME CHAR(100),IN P_EMAIL CHAR(100))
BEGIN
	INSERT INTO CUSTOMER
	VALUES
	(P_ID,p_NAME,P_EMAIL);
END //
DELIMITER ;

call ecom.FIRST_PROCEDURE(10, 'SLKL', 'SJJKJ');
