## SUBQUERIES
USE ECOM;
SELECT * FROM DIM_PRODUCT;

SELECT AVG(UNIT_PRICE) FROM DIM_PRODUCT;
SELECT * FROM DIM_PRODUCT
WHERE 
	UNIT_PRICE > 495.79;
    
-- COMBINE ABOVE BOTH QUERY IN SINGLE QUERIES AS SUBQUERY
SELECT * FROM DIM_PRODUCT
WHERE 
	UNIT_PRICE > (SELECT AVG(UNIT_PRICE) FROM DIM_PRODUCT);
    
SELECT
* 
FROM 
(
SELECT * FROM DIM_PRODUCT
WHERE 
	UNIT_PRICE > (SELECT AVG(UNIT_PRICE) FROM DIM_PRODUCT)
) AS SUBQUERY_TABLE
WHERE
PRODUCT_NAME='FIGURE METHOD';
