##CHAP:8 WINDOW FUNCTIONS ##
 /*
 WINDOW FUNCTIONS IN SQL ARE SPECIAL FUNCTIONS THAT PERFORM CALCULATIONS ACROSS A SET OF ROWS- 
 BUT WITHOUT COLLAPSING THEM INTO A SINGLE OUTPUT ROW(UNLIKE AGGREAGATE FUNCTION).
-- THEY ALLOW YOU TO DO THIGS LIKE RANKING,
MOVING AVERAGE, RUNNINN TOTAL, AND COMPARISION BETWEEN ROWS WHILE STILL KEEPING ALL THE ROWS IN THE RESULT. 
*/

SELECT * FROM DIM_PRODUCT;
-- RUNIING TOTAL BY UNIT_PRICE
SELECT *,
	SUM(UNIT_PRICE) OVER (ORDER BY UNIT_PRICE) 'RUNNING_SUM'
FROM DIM_PRODUCT;

-- RUNNING TOTAL BY LAUNCH DATE
SELECT *,
	SUM(UNIT_PRICE) OVER (ORDER BY LAUNCH_DATE) 'RUNNING_TOTAL'
FROM DIM_PRODUCT;
-- RUNNING AVERAGE
SELECT *,
	AVG(UNIT_PRICE) OVER (ORDER BY LAUNCH_DATE ) 'RUNNING_AVERAGE'
FROM DIM_PRODUCT;

SELECT *,
	SUM(UNIT_PRICE) OVER (ORDER BY LAUNCH_DATE ROWS BETWEEN UNBOUNDED preceding AND current row) 'RUNNING SUM'
FROM DIM_PRODUCT;

-- FRAMES
SELECT *,
	SUM(UNIT_PRICE) OVER (ORDER BY LAUNCH_DATE ROWS BETWEEN UNBOUNDED preceding AND unbounded following) 'TOTAL_SUM'
FROM DIM_PRODUCT;

## RANKING FUNCTION
/*
1. ROW NUMBER():Assigns a unique sequential integer to rows within a partition. 
Unlike RANK() and DENSE_RANK(), it does not account for ties; each row gets a unique number regardless of duplicates.
2. RANGE():Assigns a unique rank number to each distinct row within a partition.
 If two or more rows have the same value, they receive the same rank, but the next rank(s) will skip numbers.
3.DENSE_RANGE():Similar to RANK(), but it does not skip ranks when there are ties.
 If two rows have the same rank, the next rank will be consecutive.
*/

select 
	*,
	UNIT_PRICE,
    row_number() OVER (ORDER BY UNIT_PRICE) AS 'ROW_NUMBER',
    RANK() OVER(ORDER BY UNIT_PRICE) AS 'RANK',
    DENSE_RANK() OVER(ORDER BY UNIT_PRICE) "DENSE_RANK"
FROM DIM_PRODUCT;

# PARTITION BY
select 
	UNIT_PRICE,
    CATEGORY,
    row_number() OVER (partition by CATEGORY ORDER BY UNIT_PRICE) AS 'ROW_NUMBER',
    RANK() OVER(partition by  CATEGORY ORDER BY UNIT_PRICE) AS 'RANK',
    DENSE_RANK() OVER(partition by  CATEGORY ORDER BY UNIT_PRICE) "DENSE_RANK"
FROM DIM_PRODUCT;