## CONDITIONALS
SELECT * FROM DIM_PRODUCT;

SELECT 
	*,
	CASE
	WHEN UNIT_PRICE <= 100 THEN "AFFORDABLE"
	WHEN UNIT_PRICE <= 200 THEN " NORMAL"
    ELSE "EXPENSIVE(BUT NOT FOR YOU!)"
    END AS "PRICE_CATEGORY"
FROM
	dim_product;

-- CONDITION WITH CONCAT FUNCTION
SELECT 
	*,
	CASE
	WHEN UNIT_PRICE <= 100 AND CATEGORY="CLOTHING" THEN "AFFORDABLE"
	WHEN UNIT_PRICE <= 200 AND CATEGORY = "CLOTHING" THEN " NORMAL"
	WHEN UNIT_PRICE > 200 AND CATEGORY = "CLOTHING" THEN " EXPENSIVE(BUT NOT FOR YOU!)"
	ELSE CONCAT('NOT FOR', " " ,CATEGORY)
    END AS "PRICE_CATEGORY"
FROM
	dim_product;
    
-- CREATE 3 CONDITIONAL CRATERIA

SELECT * FROM FACT_SALES;
SELECT * FROM FACT_SALES
ORDER BY 
	UNIT_PRICE DESC;

-- 1. Categorize Sales Performance Based on Total Amount

SELECT * FROM FACT_SALES
ORDER BY 
	TOTAL_AMOUNT DESC;
    
SELECT 
	*,
    CASE
		WHEN TOTAL_AMOUNT >60 THEN 'HIGH SALES'
		WHEN TOTAL_AMOUNT BETWEEN 30 AND 50 THEN "MEDIUM SALES"
		ELSE 'LOW SALES'
    END AS SLAES_CATEGORY
FROM FACT_SALES;

## 2. Flag Discounts as Generous, Normal, or None
SELECT * FROM FACT_SALES
ORDER BY 
	DISCOUNT DESC ;

SELECT 
	*,
    CASE
		WHEN DISCOUNT >=40 THEN 'High Discount'
		WHEN DISCOUNT BETWEEN 10 AND 39 THEN 'MODERATE Discount'
		WHEN DISCOUNT <=10 THEN 'LOW Discount'
        ELSE 'O DISCOUNT'
    END AS DISCOUNT_TYPE
FROM FACT_SALES;

## 3. Combine Conditions: Profitability or Loss Check
SELECT
*,
CASE
	WHEN total_amount < 0 THEN 'Invalid Sale'
	WHEN total_amount >= (quantity_sold * unit_price) - discount THEN 'Profitable'
	ELSE 'Less Profitable'
END AS profit_status
FROM FACT_SALES;