##CHAP 10: CTES (COMMON TABLE EXPRESSIONS)

/*
In SQL, a Common Table Expression (CTE) is an essential tool for simplifying complex queries and 
making them more readable. By defining temporary result sets that can be referenced multiple times,
a CTE in SQL allows developers to break down complicated logic into manageable parts.
*/

# SUBQUERY

SELECT * FROM DIM_PRODUCT
WHERE 
	UNIT_PRICE > (SELECT AVG(UNIT_PRICE) FROM DIM_PRODUCT);

##CTE

WITH CTE_TABLE AS
(
SELECT * FROM DIM_PRODUCT
WHERE 
	UNIT_PRICE > (SELECT AVG(UNIT_PRICE) FROM DIM_PRODUCT)
)
SELECT * FROM CTE_TABLE;

-- CONDITION
WITH CTE_TABLE AS
(
SELECT * FROM DIM_PRODUCT
WHERE 
	UNIT_PRICE > (SELECT AVG(UNIT_PRICE) FROM DIM_PRODUCT)
)
SELECT * FROM CTE_TABLE
WHERE
PRODUCT_NAME='FIGURE METHOD';

-- CONDITIONFOR FILTER

WITH CTE_TABLE AS
(
SELECT * FROM DIM_PRODUCT
WHERE 
	UNIT_PRICE > (SELECT AVG(UNIT_PRICE) FROM DIM_PRODUCT)
)
SELECT * FROM CTE_TABLE
WHERE
PRODUCT_NAME IN('FIGURE METHOD','HUGE CHANGE','FILM FINALLY');

## CTE INSIDE THE CTE
WITH CTE_TABLE AS
(
SELECT * FROM DIM_PRODUCT
WHERE 
	UNIT_PRICE > (SELECT AVG(UNIT_PRICE) FROM DIM_PRODUCT)
),
CTE_TABLE_2 AS
(
SELECT * FROM CTE_TABLE
WHERE
PRODUCT_NAME IN('FIGURE METHOD','HUGE CHANGE','FILM FINALLY')
)
SELECT * FROM CTE_TABLE_2
WHERE
	PRODUCT_NAME = 'FIGURE METHOD';
