##VIEWS

CREATE view DEDUP_VIEW AS
SELECT SUBQUERY.*
FROM
(SELECT *,
	ROW_NUMBER() OVER(PARTITION BY CustomerID ORDER BY CustomerID)AS DEDUP
FROM
	CUSTOMER
)SUBQUERY
 WHERE 
	DEDUP = 1 ;
    
SELECT * FROM dedup_view;