## CONDITIONALS
SELECT * FROM DIM_PRODUCT;

SELECT 
	*,
	CASE
	WHEN UNIT_PRICE <= 100 THEN "AFFORDABLE"
	WHEN UNIT_PRICE <= 200 THEN " NORMAL"
    ELSE "EXPENSIVE(BUT NOT FOR YOU!)"
    END AS "PRICE_CATEGORY"
FROM
	dim_product;

-- 
SELECT 
	*,
	CASE
	WHEN UNIT_PRICE <= 100 AND CATEGORY="CLOTHING" THEN "AFFORDABLE"
	WHEN UNIT_PRICE <= 200 AND CATEGORY = "CLOTHING" THEN " NORMAL"
	WHEN UNIT_PRICE > 200 AND CATEGORY = "CLOTHING" THEN " EXPENSIVE(BUT NOT FOR YOU!)"
	ELSE CONCAT('NOT FOR', " " ,CATEGORY)
    END AS "PRICE_CATEGORY"
FROM
	dim_product;