# REAL TIME SCENARIOS

-- SCENARO 1[FINDING THE NTH VALUES]
SELECT * FROM DIM_PRODUCT;

SELECT
	*,
	DENSE_RANK() OVER(ORDER BY UNIT_PRICE) AS RANKING
FROM
	dim_product;
    
--  5TH PRODUCT

SELECT
	SUBQUERY.*
    FROM
(
SELECT
	*,
	DENSE_RANK() OVER(ORDER BY UNIT_PRICE) AS RANKING
FROM
	dim_product
)SUBQUERY
WHERE
RANKING = 5;

-- 5TH PRODUCT IN EACH CATEGORY
SELECT
	SUBQUERY.*
    FROM
(
SELECT
	*,
	DENSE_RANK() OVER(partition by CATEGORY ORDER BY UNIT_PRICE DESC) AS RANKING
FROM
	dim_product
)SUBQUERY
WHERE
RANKING = 5;

-- SCENARO 2[REMOVING DUPLICATES]==DE-DUPLIACATE

SELECT * FROM CUSTOMER;
INSERT INTO customer 
VALUES
(301,	'ram'	,'cc');

SELECT *,
	ROW_NUMBER() OVER(PARTITION BY CustomerID ORDER BY CustomerID)AS DEDUP
FROM CUSTOMER;

-- USING DEDUP
SELECT SUBQUERY.*
FROM
(SELECT *,
	ROW_NUMBER() OVER(PARTITION BY CustomerID ORDER BY CustomerID)AS DEDUP
FROM
	CUSTOMER
)SUBQUERY
 WHERE 
	DEDUP = 1 ;

-- SCENARIO 3 [LAG AND LEAD]
CREATE TABLE WEATHER(
ID INT,
TEMP float
);

insert INTO WEATHER VALUES
(1,10),
(2,12),
(3,14),
(4,10),
(5,40),
(6,15),
(7,17);

SELECT * FROM weather;

-- LAG BY 1 DAY AND 1 DAY AHEAD
SELECT
*,
LAG(TEMP,1) OVER(ORDER BY ID ASC) AS PREV_DAY_TEMP,
LEAD(TEMP,1) OVER(ORDER BY ID ASC) AS NEXT_DAY_TEMP
FROM
	WEATHER;
-- USING DEFULT VALUE 0 INPLACE OF NULL
SELECT
*,
LAG(TEMP,1,0) OVER(ORDER BY ID ASC) AS PREV_DAY_TEMP,
LAG(TEMP,2,0) OVER(ORDER BY ID ASC) AS PREV_2DAY_TEMP,
LEAD(TEMP,1,0) OVER(ORDER BY ID ASC) AS NEXT_DAY_TEMP
FROM
	WEATHER;
