## FUNCTIONS IN SQL

/*
FUNCTION IN SQL ARE PREDEFINED OR USERDEFINED ROUTINES THATPERFORM OPERSTIONS ON DATA
AND RETURN A SINGLE VALUE. THEY ARE VERY USEFUL FOR MANIPULATIONS, AND SIMPLIFYING QUERIES.
*/

DELIMITER //
CREATE FUNCTION SQUARE_IT(X INT)
RETURNS INT
DETERMINISTIC
BEGIN
	RETURN X*X;
END //

DELIMITER ;

SELECT
	UNIT_PRICE,
    SQUARE_IT(UNIT_PRICE)
FROM
	DIM_PRODUCT;
